### ISSUE TITLE
Deleting model from HuggingFace

### ISSUE THREAD

**Issue by davidgasquez** [borisdayma/huggingtweets#15]
This library is awesome! One thing though is that creates a public model in huggingface. I don't plan to do it, but I was wondering if it is possible to delete them easily.

**Comment by borisdayma** [comment]
That's a good point!
Actually it's not very hard to remove and feel free to let me know if there's any model you want me to remove.
I'll leave it open to remind me to add an easy way to remove models.

**Comment by ilomon10** [comment]
**Note**: You need to install `huggingface_hub` from `transformers`
```notebook
!pip install transformers
```

then create new file `delete_tf_model.py`

```python
# delete_tf_model.py

from huggingface_hub.hf_api import HfApi

hfapi = HfApi()
model_name = "YOUR_MODEL"
user, namespace = 'huggingtweets-app', 'huggingtweets'
token = hfapi.login(user, namespace)
assert hfapi.whoami(token)['name'] == user, "Could not log into Hugging Face"
hfapi.delete_repo(token=token, name=model_name, organization=namespace)
```

It works for me!
