### ISSUE TITLE
Train on gpt2 arabic or AraBERT 

### ISSUE THREAD

**Issue by thezem** [borisdayma/huggingtweets#20]
i'm trying to train huggingtweets with arabic models , i've tried everything and every arabic model out there but nothing seems to work

![94](https://user-images.githubusercontent.com/65074998/130800922-2fa91a6b-c37c-4b85-9e0b-b1295e96891a.PNG)

it always gives this error:

`An error occured...
num_samples should be a positive integer value, but got num_samples=0`

even if tried to change the block size , same thing happens , is there anyway to make this work?

**Comment by borisdayma** [comment]
May be related to #19
